name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Docker image
      run:  |
        docker login --username 8-prime --password ${{ secrets.GH_PAT }}
        docker build . --tag ghcr.io/8-prime/file-flow:latest
        docker push ghcr.io/8-prime/file-flow:latest
